spring:
  profiles:
    active: dev
###################  mybatis配置  ###################
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.shixun.sduvideo.domain.dto
  configuration:
    map-underscore-to-camel-case: true
