server:
  port: 8888

###################  spring配置  ###################
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 主库数据源
      master:
      url: jdbc:mysql://xxxxxxxxx:3306/sduvideo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: xxxxx
      password: xxxxx
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 5
      # 最大连接池数量
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 6 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

  session:
    store-type: redis  # 配置Session的存储方式为Redis

# Swagger配置
swagger:
  enabled: true
    # 请求前缀
  pathMapping: /dev-api

